### ISSUE TITLE
Key rebinding

### ISSUE THREAD

**Issue by EasterncheesE** [Nogg-aholic/PowerSuit#11]
Hi there. Can you please add possibility to rebind mod keys in config file?
So far, i use alternative controls for game, thus mod keys interfere with buttons that are configured for other actions in my control bindings.

**Comment by mtfurlan** [comment]
I use a kinesis advantage keyboard.
I don't have a right alt button.

I would really appreciate the ability to rebind keys so I can actually try this mod.

**Comment by budak7273** [comment]
The next SML version will release some extra keybind features which we are waiting on to implement key rebinding. You can read more [here](https://github.com/Nogg-aholic/PowerSuit/issues/4#issuecomment-742450934).

In the mean time, you may be able to use something like [AutoHotKey](https://www.autohotkey.com/docs/misc/Remap.htm) to rebind another key to Right Alt, for example, and open the suit UI that way.

**Comment by Miranina** [comment]
There was a change though in the keybind, the mod was previously using the "crouch".

Any idea if the double tap to activate and deactivate the hover will ever come back ? ~~I can't find a way to turn off hover mode anymore.~~ Found it in a patch note in the modules, still would prefer the double tap though.

Using the left Alt key also interfere with Smart Foundation that use it to expand in a certain axis ( noticed it was mentionned in another comment ).

~~I might have missed a patch note as to why the previous keybinds were changed, since they weren't a problem before ?~~ found a mention of a new feature for powered descent but the crouch was doing it before ?

**Comment by budak7273** [comment]
Closing this issue as it was resolved by the SML3 update which brought SML keybinding support.
