### ISSUE TITLE
Support for linux

### ISSUE THREAD

**Issue by Ectalite** [Nogg-aholic/PowerSuit#28]
Hi,

I know that the mod has bugs in multiplayer but I wanted to check it anyways on my headless server.
When I started the server, I got the error:
`[2021.12.27-13.35.28:148][  0]LogLinux: Warning: MessageBox: Plugin 'PowerSuit' failed to load because module 'PowerSuit' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.`
I checked then why I didn't recognized the mod and I saw that you only compiled the mod for windows (and my server is running linux which is obviously not working).

I would then ask if you could compile it for linux ?

Thanks,
Ectalite

**Comment by budak7273** [comment]
Hi,

As it looks like you already found out in the Discord, no mods work on dedicated servers at them moment because SML itself is not compiled for Linux. The SML team is working on this issue; we'll compile for Linux once they do as well. I believe the current trouble point on their side is getting hooking to work correctly.
